### ISSUE TITLE
USER STORY: Make changes in bag

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#10]
Epic: Purchasing and Checkout

As a **customer** I can **adjust the dates and number of guests for a trip in the bag** so I can **make changes just before checkout**

# Acceptance Criteria:
* Acceptance Criteria 1: The bag page will have a form with the ability to update the number of guests and dates
* Acceptance Criteria 2: This will be able to be completed directly from the bag without navigating away 
* Acceptance Criteria 3: The bag will then reload and the cost/changes will be updated accordingly

# Tasks:
- [x] Task 1: Change the bag.html to include a form of POST request to change the quantity and dates
- [x] Task 2: Create 'change bag' view with logic to calculate the new total cost
- [x] Task 3: Create 'change bag' URL
