### ISSUE TITLE
USER STORY: View bag

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#12]
Epic: Purchasing and Checkout

As a **customer** I can **view the items in my bag** so I can **identify the total cost of my purchase and details of every trip I am buying**

# Acceptance Criteria:
* Acceptance Criteria 1: Checkout button will open a new page to show what is in the bag
* Acceptance Criteria 2: Bag page will list a breakdown of the items, with cost and a total cost at the bottom
* Acceptance Criteria 3: A preview of what is in the bag can be seen from a dropdown in the header/navbar 

# Tasks:
- [x] Task 1: Create bag app and bag model
- [x] Task 2: Create 'view bag' view with logic to calculate total cost
- [x] Task 3: Create 'view bag' URL
- [x] Task 4: Update main app URLs to include bag URLs
- [x] Task 5: Create view bag template
- [x] Task 6: Update base/index.html navbar to add preview of bag view
- [ ] Task 7: Add JavaScript to show preview of bag view everytime an item is added or hovered over
