### ISSUE TITLE
USER STORY: Select dates/guests

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#13]
Epics: Purchasing and Checkout

As a **customer** I can **easily select the dates and number of guests attending a trip** so I can **ensure I don't accidentally select the wrong trip or booking information**

# Acceptance Criteria:
* Acceptance Criteria 1: Customers can select a date within specific months for each trip, using a date selector tab
* Acceptance Criteria 2: The number of guests can be selected between 1 and the maximum number available for the tour
* Acceptance Criteria 3: The number of guests and date can be seen in the bag
* Acceptance Criteria 4: The number of guests can be changed in the bag app.

# Tasks:
- [x] Task 1: Add a date model with a many-to-many relationship to each tour
- [x] Task 2: Add the many-to-relationship in the tour model with choices to select specific months
- [x]  Task 3: Add a new tab named dates, which will open 2023 and 2024 then the months selected in the tour model field, wrapped in a form tag
- [x] Task 4: Add two new include pages with buttons for 28 to 31 days depending on the number of days in the month
- [x] Task 5: Add the JQuery code to allow the tabs to open and be selected when the buttons are clicked
- [x] Task 6: Add the number of travellers input inside the form along with plus and minus buttons
- [x] Task 7: Add the jQuery code to increase/decrease the input and limit to the max number of guests allowed
- [x] Task 8: Create an add_to_bag view with the logic to calculate and add the 'quantity' to the bag
