### ISSUE TITLE
USER STORY: Personalise Profile

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#19]
Epic: Registration and Sign-in

As a **site user** I can **personalise my profile** so I can **view my personal order history/order confirmations and save my payment information**

# Acceptance Criteria:
* Acceptance Criteria 1: Each user will have a personal profile page where they can add private billing information
* Acceptance Criteria 2: The page will also show a breakdown of order history

# Tasks:
- [x] Task 1: Create a profile app, with a profile model using the django user model as a one to one field.
- [x] Task 2: Add a profile view, URL and hook up to main URLs
- [x] Task 3: Create a profile form in forms.py where the user can send specific info, e.g. address and phone number to the view in a POST request
- [x] Task 4: Create a profile template in which the form is rendered to accept the new information, or updated information
