### ISSUE TITLE
USER STORY: Email confirmation - registration

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#20]
Epic: Registration and Sign in

As a **site user** I can **receive an email confirmation after registering** so I can **verify my account registration was successful**

# Acceptance Criteria:
* Acceptance Criteria 1: Upon successful registration the customer will receive an email asking them to verify their address

# Tasks:
- [x] Task 1: Create two text files one for the subject, another for the body of the email
- [x] Task 2: In webhook_handler, once the registration has been successful call the send_email function, passing in the templates, the send to email and the from email
- [x] Task 3: Get the customer email from the signup form and in settings.py create a variable for the send from email
