### ISSUE TITLE
USER STORY: Login/logout

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#22]
Epic: Registration and Sign-in

As a **site user** I can **login and logout** so I can **access my personal/private account information**

# Acceptance Criteria:
* Acceptance Criteria 1: The user can click the login/logout button on the nav bar of any page
* Acceptance Criteria 2: There will be a dedicated login/logout form to submit to login to their profile
* Acceptance Criteria 3: A success message stated they have logged in successfully or they entered their email/password incorrectly will be displayed upon submitting the form
* Acceptance Criteria 4: Once logged in they will be able to view their own private profile page

# Tasks:
- [x] Task 1: Create the login/logout view with a GET and POST request
- [x] Task 2: Create the login/logout URL
- [x] Task 3: Add a login/logout template
- [x] Task 4: Update the base/index.html template to include a login/logout button in the header/nav bar
- [x] Task 5: Create a profile page view with a GET request
- [x] Task 6: Create the profile page URL
- [x] Task 7: Add a profile page template
