### ISSUE TITLE
USER STORY: Register

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#23]
Epic: Registration and Sign-in

As a **site user** I can **register for an account** so I can **have a personal account and be able to view my profile**

# Acceptance Criteria:
* Acceptance Criteria 1: A register page with a brief form will be accessible from the nav bar on all pages
* Acceptance Criteria 2: The form will be submitted after collecting the required information (name, email address, password)
* Acceptance Criteria 3: The form will contain optional info (phone number, address etc)
* Acceptance Criteria 4: The form will be submitted using a Signup now button

# Tasks:
- [x] Task 1: Create a user/profile model
- [x] Task 2: Create an add user view, with a GET and POST request
- [x] Task 3: Create an add user URL
- [x] Task 4: Update the main app URLs to include the user/profile URL
- [x] Task 5: Create the add user form
- [x] Task 6: Create an add user template
- [x] Task 7: Update the base/index.html template to include the signup button in the header/nav bar
