### ISSUE TITLE
USER STORY: View bag price

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#24]
As a **customer** I can **view the total of my purchases at any time** so I can **avoid spending too much**

# Acceptance Criteria:
* Acceptance Criteria 1: The bag icon/dropdown will be updated as each product is added to the bag
* Acceptance Criteria 2: The bag icon will be visible on all pages when logged in
* Acceptance Criteria 3: The bag cost will be displayed when each product is added and when the user hovers over the icon

# Tasks:
- [x] Task 1: Update the base/index.html templates to display the price and bag icon
- [x] Task 2: Update the bag view to include messages when a new item is added to the bag
- [x] Task 3: Add JavaScript to display 'snapshot' of bag when hovered over by user
