### ISSUE TITLE
USER STORY: Find Deals

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#25]
As a **customer** I can **identify packages/deals/group rates** so I can **take advantages of special savings**

# Acceptance Criteria:
* Acceptance Criteria 1: Deals should be displayed on homepage
* Acceptance Criteria 2: Any additional requirements to products to receive deal should be displayed on individual product pages, checkout page and bag page
* Acceptance Criteria 3: A message reminding customers they are close to a deal should pop up explaining what criteria is needed to be met

# Tasks:
- [ ] Task 1: Update index.html/base.html to include an overlay/modal displaying the deals available and messages
- [ ] Task 2: Update product detail/product list view to add logic to calculate requirements for deal
- [ ] Task 3: Update product detail/product list view to add messages for deal
- [ ] Task 4: Update product detail/product list template to add a location for deal
