### ISSUE TITLE
USER STORY: View Individual Products

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#26]
Epic: Products

As a **customer** I can **view individual products** so I can **identify price, description, location and timeframe**

# Acceptance Criteria:
* Acceptance Criteria 1: The page should display only the individual product
* Acceptance Criteria 2: The name, description, and stock photo should be displayed
* Acceptance Criteria 3: The date selector and number of guest buttons should be displayed and able to be selected
* Acceptance Criteria 4: There should be an 'add to bag' button

# Tasks:
- [x] Task 1: Create the product model
- [x] Task 2: Create a product detail view
- [x] Task 3: Create a product detail url
- [x] Task 4: Create a product detail template and CSS
- [x] Task 5: Add JavaScript to enable date selector and number of guest buttons to work
- [x] Task 6: Update main app URLs to include product URLs
