### ISSUE TITLE
USER STORY: View Products

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#27]
Epic: Products

As a **customer** I can **view a list of products** so I can **select some to purchase**

# Acceptance Criteria:
* Acceptance Criteria 1: The available products should be displayed in list/table form on one page
* Acceptance Criteria 2: The products should be clickable
* Acceptance Criteria 3: The basic product information should be displayed near each product name

# Tasks:
- [x] Task 1: Create a product list view
- [x] Task 2: Create a product list url
- [x] Task 3: Create a product list template
