### ISSUE TITLE
USER STORY: Login via Facebook/Google/Apple

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#28]
Epic: Registration and Signin

As a **customer** I can **login and register using my pre-exsiting facebook/gmail/apple accounts** so I can **link my emails and accounts into one for a more streamlined service**

# Acceptance Criteria:
* Acceptance Criteria 1: Upon clicking register links/buttons to register via facebook/gmail/apple will be displayed.
* Acceptance Criteria 2: These links will open a pop-up to sign into the accounts and pre-populate the registration form

# Tasks:
- [ ] Task 1: Add django-allauth for the relevant social media providers
- [ ] Task 2: Gather the API keys, secret keys etc and enter into the django admin section
- [ ] Task 3: In the register/sign in templates add the buttons required to link to the pop ups.
