### ISSUE TITLE
USER STORY: Delete Products

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#33]
Epic: Admin and Store Management

As a **owner** I can **delete products** so I can **remove products no longer in stock and keep my store up to date**

# Acceptance Criteria:
* Acceptance Criteria 1: A delete product button will be shown next to each product on both the lists and details pages
* Acceptance Criteria 2: The delete product button will have to be confirmed to avoid deleting products by mistake

# Tasks:
- [x] Task 1: Add a delete_product view into views.py
- [x] Task 2: Add a delete_product URL into urls.py 
- [x] Task3: Update the product list and detail pages to include a delete button
- [x] Task4: Create a 'are you sure' popup to complete the delete form for defensive programming
