### ISSUE TITLE
USER STORY: Homepage

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#34]
Epic: Admin and Store Management

As a **site user** I can **see a clear and interesting homepage** so I can **understand the meaning of the site and how to make a purchase**

# Acceptance Criteria:
* Acceptance Criteria 1: The homepage will have a clear header with tabs and dropdowns leading to relevant pages
* Acceptance Criteria 2: The bag will be accessible via the header
* Acceptance Criteria 3: There will be a large hero image drawing the user in
* Acceptance Criteria 4: A footer will be present with links to social media and information about the company

# Tasks:
- [x] Task 1: Create a home app adding a new urls.py file
- [x] Task 2: Create a homepage view with a get request
- [x] Task 3: Add a homepage url
- [x] Task4: Create a base template and a homepage template
