### ISSUE TITLE
USER STORY: Messages/notifications

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#37]
Epic: Store Admin and Management

As a **site user** I can **see messages/notifications when I perform a task** so I can **be confident that the task has been completed correctly**

# Acceptance Criteria:
* Acceptance Criteria 1: Upon successful completion, failure or an error of any function the user will be displayed a message in the top corner
* Acceptance Criteria 2: The messages about the bag will also display the contents of the bag

# Tasks:
- [x] Task 1: In the base.html page add a messages div where the messages will be displayed
- [x] Task 2: Using the bootstrap toasts add HTML files for each message, success error etc and link the levels into the message div
- [x] Task 3: When/wherever a message is to be displayed add this to the relevant view with the desired message and HTTP response
- [x] Task 4: in the toast HTML file for the bag success add the template tags and styling to display a snapshot of the bag
