### ISSUE TITLE
USER STORY: Accept Payments

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#38]
Epic: Purchasing and Checkout

As a **customer** I can **pay online by card** so I can **order my products easily without having to contact a sales representative**

# Acceptance Criteria:
* Acceptance Criteria 1: A checkout form with card payment section will be available to fill in
* Acceptance Criteria 2: If required the customer can perform extra security checks

# Tasks:
- [x] Task 1: Set up a stripe account and enter the API keys into the settings (put the secret key in environment variables)
- [x] Task 2: Add Stripe HTML to the checkout page
- [x] Task 3: Add Stripe JS generate form fields
- [x] Task 4: Add payment intents to checkout views
- [x] Task 5: Style stripe section of form to match the rest of the checkout form
