### ISSUE TITLE
USER STORY: Email confirmation - purchase

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#6]
Epic: Purchasing and Checkout

As a **customer** I can **receive an email confirmation** so I can **have a record of my purchases**

# Acceptance Criteria:
* Acceptance Criteria 1: Upon successful order the customer will receive a confirmation email with a breakdown of their order

# Tasks:
- [x] Task 1: In the webhook_handler.py create a new function to render and send an email when called
- [x] Task 2: Create two text files one for the subject, another for the body of the email
- [x] Task 3: In webhook_handler, once the payment has been successfully processed call the new send_email function, passing in the templates, the send to email and the from email
- [ x] Task 4: Get the customer email from the order form and in settings.py create a variable for the send from email
