### ISSUE TITLE
USER STORY: View order confirmation

### ISSUE THREAD

**Issue by tdawes93** [tdawes93/MyWay#7]
Epic: Purchasing and Checkout

As a **customer** I can **see an order confirmation** so I can **check I haven't made any mistakes when completing a purchase**

# Acceptance Criteria:
* Acceptance Criteria 1: An order confirmation page will be loaded upon successful purchase
* Acceptance Criteria 2: It will display information related to the purchase
* Acceptance Criteria 3: If logged in the customer will be able to see historical orders

# Tasks:
- [x] Task 1: Add a view, URL and template for a checkout_success page.
- [x] Task 2: Link the URL to the checkout URLs
- [x] Task 3: Add a context so the checkout success page will display specific information for the purchase
